// Dropdown options
final List<String> regions = [
  "All",
  "Tunis",
  "Ariana",
  "Ben Arous",
  "Manouba",
  "Nabeul",
  "Zaghouan",
  "Bizerte",
  "Beja",
  "Jendouba",
  "Kef",
  "Siliana",
  "Sousse",
  "Monastir",
  "Mahdia",
  "Sfax",
  "Kairouan",
  "Kasserine",
  "Sidi Bouzid",
  "Gabes",
  "Medenine",
  "Tataouine",
  "Gafsa",
  "Tozeur",
  "Kebili",
];

final Map<String, List<String>> cities = {
  "All": ["All"],
  "Tunis": ["Tunis", "Carthage", "La Marsa"],
  "Ariana": ["Ariana", "Raoued", "Soukra", "Borj Baccouche"],
  "Ben Arous": ["Ben Arous", "Hammam-Lif", "Radès"],
  "Manouba": ["Manouba", "Douar Hicher", "Oued Ellil"],
  "Nabeul": ["Nabeul", "Hammamet", "Kelibia"],
  "Zaghouan": ["Zaghouan", "El Fahs", "Zriba"],
  "Bizerte": ["Bizerte", "Menzel Bourguiba", "Ras Jebel"],
  "Beja": ["Beja", "Teboursouk", "Testour"],
  "Jendouba": ["Jendouba", "Bou Salem", "Tabarka"],
  "Kef": ["Kef", "Dahmani", "Tajerouine"],
  "Siliana": ["Siliana", "Bargou", "El Krib"],
  "Sousse": ["Sousse", "Hammam Sousse", "Akouda"],
  "Monastir": ["Monastir", "Sahline", "Jemmel"],
  "Mahdia": ["Mahdia", "Chebba", "Ksour Essef"],
  "Sfax": ["Sfax", "Sakiet Ezzit", "Mahrès"],
  "Kairouan": ["Kairouan", "Haffouz", "Sbikha"],
  "Kasserine": ["Kasserine", "Sbeitla", "Feriana"],
  "Sidi Bouzid": ["Sidi Bouzid", "Regueb", "Meknassy"],
  "Gabes": ["Gabes", "Mareth", "Matmata"],
  "Medenine": ["Medenine", "Djerba", "Ben Guerdane"],
  "Tataouine": ["Tataouine", "Ghomrassen", "Bir Lahmar"],
  "Gafsa": ["Gafsa", "Metlaoui", "Redeyef"],
  "Tozeur": ["Tozeur", "Nefta", "Degache"],
  "Kebili": ["Kebili", "Douz", "Souk Lahad"],
};

final List<String> specializations = [
  "All",
  "General Practitioner",
  "Cardiologist",
  "Dermatologist",
  "Dentist",
  "Pediatrician",
];
